### PR TITLE
Prepare for Heroku

### PR DESCRIPTION
**Pull request by jkutner**
You may not want to merge this exactly, but I wanted to share since this is how I got it working. With these changes you can run:

```
$ git clone https://github.com/jkutner/cbioportal
$ cd cbioportal
$ heroku create
$ heroku config:set PORTAL_HOME=/app
$ heroku addons:create cleardb
$ heroku config:get CLEARDB_DATABASE_URL
# export JDBC_DATABASE_URL,USERNAME,PASSWORD based on ^^
$ mvn install -DskipTests
$ heroku plugins:install https://github.com/heroku/heroku-deploy
$ heroku deploy:war --war portal/target/cbioportal.war
$ heroku open
$ heroku logs -t
```

If you'd prefer to deploy with Git, you'll need to make some kind of change with PORTAL_HOME because this value will be different between build time and run time. At build time, it will be a `/tmp` dir and runtime it will be `/app`. I think you could substitute `System.getProperty("user.dir");`

Once you can deploy with Git, you can add a [Heroku Button](https://blog.heroku.com/archives/2014/8/7/heroku-button) so that it can be deployed with one click. 

You could also configure this to use the [heroku-maven-plugin](https://github.com/heroku/heroku-maven-plugin) instead of the `heroku deploy:war` command. That would be a trivial change.

### CODE REVIEW

**Comment by inodb** [comment]
Excellent! This is super useful!

I am actually looking to deploy with Git. What do you mean by substitute `System.getProperty("user.dir")`? Substitute `PORTAL_HOME` by that? Isn't there some repo root variable that I could set `PORTAL_HOME` to?

**Comment by jkutner** [comment]
@inodb i think you could set it to `$HOME`, but that might be tricky at build time. Let me take a look and see.

**Comment by jkutner** [comment]
I've updated to fix the Git stuff. Sorry about the the whitespace changes. You should be able to deploy my branch with:

```
$ heroku create
$ heroku buildpacks:add https://github.com/jkutner/cbioportal-buildpack
$ heroku buildpacks:add heroku/java
$ git push heroku master
```

**Comment by inodb** [comment]
Thanks a lot for the help! I managed to add your suggestions. I will close this PR now to see if the Heroku's Review Apps will automatically close it.

**Pull request closed without merging**
